Created Compound Query for Collection
odu-emse/emseAPI pull request #447
Opened 2023-02-15 20:03 UTC by kenny-dd

1. Modified service file to have one instance of collection instead of collection and collections
2. Added id as a query parameter 
3. Modified test cases that gave errors from deleted "collections" service

2023-02-21 18:11 UTC, frontoge approved these changes

2023-02-21 18:13 UTC, frontoge requested changes

2023-02-21 18:13 UTC, frontoge commented on src/program/program.resolver.ts
> +	async collection(@Args("input") args: CollectionFields | null = null) {
This line is causing the build to fail, needs to be fixed before Merging

2023-02-22 18:52 UTC, chef-danny-d approved these changes

2023-02-22 18:53 UTC, merged